### PR TITLE
Fix Python tests - fix #18

### LINKED ISSUE #18: Fix tests
Tests broken, probably because the latest radare2

### PR DESCRIPTION
**Pull request by XVilka**

### CODE REVIEW

**Comment by radare** [comment]
u have commit access

**Comment by XVilka** [comment]
I know, it is just not 100% ready yet.

**Comment by quim0** [comment]
Thanks for the help! I'm really afk these months but I'll try to check and contribute

**Comment by radare** [comment]
Cool!

**Pull request closed without merging**
